// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  weather: {
    api: 'https://api.openweathermap.org/data/2.5',
    appId: '9e240b063640d0cf77e34d75db435670',
    units: 'metric',
    iconUrl: '//openweathermap.org/img/w'
  },
  defaultLanguage: 'en-US',
  defaultGeo: 'Vladivostok',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
