// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  weather: {
    api: 'https://api.openweathermap.org/data/2.5',
    appId: '9e240b063640d0cf77e34d75db435670',
    units: 'metric',
    iconUrl: '//openweathermap.org/img/w'
  },
  defaultLanguage: 'en-US',
  defaultGeo: 'Vladivostok',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
